#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Std qw(getopts);
use List::Util  qw/shuffle/;
use Digest::SHA qw(sha256_hex);
use File::Spec;

my %opts;
my $fh;
my $audio_dir;
my @list = ();

getopts( 'rt:a:', \%opts );

if ( $opts{'t'} ) {
    open $fh, '<', $opts{'t'};
}
else {
    open $fh, '<-';
}

if ( $opts{'a'} ) {
    $audio_dir = $opts{'a'};
}
elsif ( -e 'audio' ) {
    $audio_dir = 'audio';
}
else {
    die;
}

while (<$fh>) {
    chomp;
    push @list, $_;
}

@list = shuffle @list unless $opts{'r'};

foreach (@list) {
    my $mp3 = File::Spec->catfile( $audio_dir, substr( sha256_hex($_), 0, 16 ) . ".mp3" );
    my $start = time();
    print "$_\n";
    system 'mpg123', '-q', $mp3;
    my $elapsed = time() - $start;
    sleep($elapsed + 0.5);
}

